/**
 * Forge the contents of an AGENTS.md from a preamble and ordered modules.
 *
 * Pure: takes strings, returns a string. File I/O lives in bin/cli.js so this
 * stays trivially testable.
 *
 * @param {object}   opts
 * @param {string}   opts.preamble  Intro text placed first.
 * @param {string[]} opts.modules   Rule modules, emitted in array order.
 * @param {string}   opts.source    Source identifier (repo URL) for the header.
 * @returns {string} Full AGENTS.md text, newline-terminated.
 */
export function generate({ preamble, modules = [], source }) {
  const header = [
    '<!-- GENERATED FILE — DO NOT EDIT.',
    `     Generated by agentsmith from ${source}.`,
    '     Edit the source instructions and re-run the generator. -->',
  ].join('\n');

  const blocks = [preamble, ...modules]
    .map((block) => String(block).trim())
    .filter(Boolean);

  return [header, ...blocks].join('\n\n') + '\n';
}
