/**
 * Forge the contents of an AGENTS.md from a preamble and ordered modules.
 *
 * Pure: takes strings, returns a string. File I/O lives in bin/cli.js so this
 * stays trivially testable.
 *
 * @param {object}   opts
 * @param {string}   opts.preamble  Intro text placed first.
 * @param {string[]} opts.modules   Rule modules, emitted in array order.
 * @param {string}   opts.source    Source identifier (repo URL) for the header.
 * @param {string}   [opts.commit]  Source commit hash; recorded in the header when given.
 * @param {string}   [opts.date]    Source commit date; recorded alongside the commit.
 * @returns {string} Full AGENTS.md text, newline-terminated.
 */
export function generate({ preamble, modules = [], source, commit, date }) {
  const header = [
    "<!-- GENERATED FILE: DO NOT EDIT.",
    `     Generated by agentsmith from ${source}.`,
    ...(commit ? [`     Source revision ${commit} (${date}).`] : []),
    "     Edit the source instructions and re-run the generator. -->",
  ].join("\n");

  const blocks = [String(preamble), ...modules.map(demoteHeadings)]
    .map((block) => block.trim())
    .filter(Boolean);

  return [header, ...blocks].join("\n\n") + "\n";
}

/**
 * Demote every ATX heading one level (`#` -> `##`, up to h5 -> h6) so an
 * inlined module's own h1 title nests under the preamble's single h1.
 *
 * Headings inside fenced code blocks (``` or ~~~) are left untouched.
 *
 * @param {string} markdown  A module's source text.
 * @returns {string} The module with its headings demoted.
 */
function demoteHeadings(markdown) {
  let inFence = false;
  return String(markdown)
    .split("\n")
    .map((line) => {
      if (/^\s*(```|~~~)/.test(line)) inFence = !inFence;
      if (inFence) return line;
      return line.replace(/^(#{1,5})(\s)/, "#$1$2");
    })
    .join("\n");
}
