// Generates docs/working-specs/INDEX.md from the working-spec corpus (#ai-plan).
// Pure functions here; bin/spec-index.js drives them. A drift test
// (test/spec-index.test.mjs) keeps the committed INDEX.md from going stale.
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const EMDASH = '—';

// Parse one spec.md -> { title, status }. title: first '# ' heading (marker
// stripped). status: first line matching /Status:/ (optionally **bold**),
// reduced to the first whitespace token of its value; EMDASH when absent.
export function parseSpec(text) {
  const lines = text.split(/\r?\n/);
  const titleLine = lines.find((l) => /^#\s+/.test(l));
  const title = titleLine ? titleLine.replace(/^#\s+/, '').trim() : '(untitled)';
  const statusLine = lines.find((l) => /^\*{0,2}Status:/i.test(l.trim()));
  let status = EMDASH;
  if (statusLine) {
    const value = statusLine.trim().replace(/^\*{0,2}Status:\*{0,2}\s*/i, '').trim();
    status = value.split(/\s+/)[0] || EMDASH;
  }
  return { title, status };
}

// Scan a working-specs directory: each child dir named YYYY-MM-DD-<slug> with a
// spec.md becomes a unit. Sorted date-desc, then slug-asc.
export function scanWorkingSpecs(dir) {
  const units = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (!e.isDirectory()) continue;
    const m = /^(\d{4}-\d{2}-\d{2})-(.+)$/.exec(e.name);
    if (!m) continue;
    let title = '(no spec.md)';
    let status = EMDASH;
    try {
      ({ title, status } = parseSpec(readFileSync(join(dir, e.name, 'spec.md'), 'utf8')));
    } catch {
      // a unit dir without spec.md keeps the placeholders
    }
    units.push({ date: m[1], slug: m[2], dir: e.name, title, status });
  }
  units.sort((a, b) => (a.date === b.date ? a.slug.localeCompare(b.slug) : b.date.localeCompare(a.date)));
  return units;
}

// Render the committed INDEX.md from pre-sorted units.
export function renderIndex(units) {
  const header =
    '# Working specs index\n\n' +
    '<!-- Generated by `node bin/spec-index.js` -- do not hand-edit. -->\n\n' +
    '| Date | Unit | Status |\n|---|---|---|\n';
  const rows = units.map((u) => `| ${u.date} | [${u.title}](${u.dir}/spec.md) | ${u.status} |`);
  return header + rows.join('\n') + '\n';
}
